export enum ErrorEnum {
  NEED_TO_LOGIN = "NEED_TO_LOGIN",
  NOT_FOUND_TOKEN = "NOT_FOUND_TOKEN",
  NOT_FOUND_ACCESS_TOKEN = "NOT_FOUND_ACCESS_TOKEN",
  NOT_FOUND_REFRESH_TOKEN = "NOT_FOUND_REFRESH_TOKEN",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
}
